### ISSUE TITLE
gui add wasm support

### ISSUE THREAD

**Issue by Waitforomething2023** [HelloWorld886/xmake-visualstudio#6]
can u add platform wasm support?

**Comment by HelloWorld886** [comment]
sure

**Comment by HelloWorld886** [comment]
v1.12 has published.

**Comment by Waitforomething2023** [comment]
> v1.12 has published.

Thank you

**Comment by Waitforomething2023** [comment]
> v1.12 has published.

I have another question about the wasm platform. It is the Intellisense find the headers from windows sdk by default,but the wasm use the emcc(or wasi) toolchain,so is it possible that change the headers search dirs to emcc sdk path?

**Comment by HelloWorld886** [comment]
The generation of compile_commands.json is provided by xmake, you can submit an issue to xmake.

**Comment by Waitforomething2023** [comment]
> The generation of compile_commands.json is provided by xmake, you can submit an issue to xmake.

OK seems bug from clangd
